name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: us-east-1
  S3BUCKET: codedeploystack-webappdeploymentbucket-pce5ra19uuag
=======
  AWS_REGION: us-east-1
  S3BUCKET: codedeploystack-webappdeploymentbucket-pce5ra19uuag


jobs:
  build:
    name: Build and Package
<<<<<<< HEAD
    runs-on: ubuntu-latest
=======
    runs-on: ubuntu-20.04
>>>>>>> dc615f3 (initial code)
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

<<<<<<< HEAD
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
=======
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.CODEDEPLOY_IAMROLE }}
>>>>>>> dc615f3 (initial code)
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: chmod
        run: chmod -R +x ./.github

      - name: Build and Package Maven
        id: package
        working-directory: ${{ env.applicationfolder }}
        run: $GITHUB_WORKSPACE/.github/scripts/build.sh

      - name: Upload Artifact to s3
        working-directory: ${{ env.applicationfolder }}/target
        run: aws s3 cp *.war s3://${{ env.S3BUCKET }}/
<<<<<<< HEAD
        
=======
>>>>>>> dc615f3 (initial code)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
<<<<<<< HEAD
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
=======
    - uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.CODEDEPLOY_IAMROLE }}
>>>>>>> dc615f3 (initial code)
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}
    - run: |
        echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
        commit_hash=`git rev-parse HEAD`
<<<<<<< HEAD
        aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
=======
        aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=[replace github repo name],commitId=$commit_hash --ignore-application-stop-failures
>>>>>>> dc615f3 (initial code)
